services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    # depends_on:
    #   - wordpress
    ports:
      - "443:443"
    volumes:
     # - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      # - wp-volume:/var/www/
    env_file:
      - ./.env
    networks:
      - inception
    restart: unless-stopped
  
  mariadb:
      build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
      container_name: mariadb
      image: mariadb
      env_file:
        - ./.env
      volumes:
        - /home/${LOGIN}/data/mariadb:/var/lib/mysql
      networks:
        - inception
      restart: unless-stopped

networks:
    inception:
        name: inception
        driver: bridge

volumes:
  mariadb-data:
