services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    # depends_on:
    #   - wordpress
    ports:
      - "443:443"
    volumes:
     # - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      # - wp-volume:/var/www/
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERT=${CERT_}
      - KEY=${KEY_}
    networks:
      - inception
    restart: unless-stopped

networks:
    inception:
        name: inception
        driver: bridge
