services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    depends_on:
    - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wordpress_data:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    restart: unless-stopped
  
  mariadb:
      build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
      container_name: mariadb
      image: mariadb
      env_file:
        - ./.env
      volumes:
        - mariadb_data:/var/lib/mysql
      networks:
        - inception
      ports:
        - "3306:3306"
      restart: unless-stopped
  
  wordpress:
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      container_name: wordpress
      image: wordpress
      env_file:
        - ./.env
      volumes:
        - wordpress_data:/var/www/html
      depends_on:
        - mariadb
      networks:
        - inception
      ports:
        - "9000:9000"
      restart: unless-stopped
  
volumes:
  wordpress_data:
  mariadb_data:

networks:
    inception:
        name: inception
        driver: bridge
